### ISSUE TITLE
[Feature Request] `cp`, but from s3?

### ISSUE THREAD

**Issue by dep** [keithweaver/aws-s3-github-action#10]
I am loving this workflow, but something I'd like to do is inverse the `cp` operation, like this:

```
- uses: keithweaver/aws-s3-github-action@v1.0.0
  with:
    command: cp
    source: s3://${{ secrets.AWS_PROD_BUCKET }}/assets
    destination: ./applications/composed-storybook/storybook-static/versions
    aws_access_key_id: ${{ secrets.AWS_PROD_S3_UPLOADER_ACCESS_KEY }}
    aws_secret_access_key: ${{ secrets.AWS_PROD_S3_UPLOADER_SECRET_KEY }}
    aws_region: us-east-1
```

so `source` being a copy-from, `destination` being a copy-to.

I could probably avoid doing this if I could set the output of `ls` to a variable or something. Any help appreciated!

**Comment by indiVar0508** [comment]
Hi,
 i was also looking for something similar to be able to download, i didn't find anything on action demo
https://github.com/keithweaver/aws-s3-github-action-demo/blob/master/.github/workflows/main.yml

**Comment by jniclas** [comment]
Hey, I tested this by simply switching source with destination and it works 👍🏻 
...at least with a single file:
```
- name: fetch dicom test data
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://bucket/file.zip
          destination: ./path/file.zip
          ...
```
