### ISSUE TITLE
Shell errors when using action

### ISSUE THREAD

**Issue by gsaraf** [keithweaver/aws-s3-github-action#4]
I am seeing shell errors when using this action:
```
Using the profile :: []
/entrypoint.sh: line 70: [: missing `]'
AWS Session Token was not found. Using configuration from previous step.
AWS Session Token was not found. Using configuration from previous step.
Metadata service timeout was not found. Using configuration from previous step.
cp: cannot stat '==': No such file or directory
cp: target ']' is not a directory
/entrypoint.sh: line 113: [: missing `]'
cp: cannot stat '==': No such file or directory
cp: target ']' is not a directory
/entrypoint.sh: line 117: aws s3  s3://raftt-resources/cli/latest : No such file or directory
```

Could it be due to missing a shebang?

My usage:
```
...
      steps:
      - id: get_cli_latest
        uses: keithweaver/aws-s3-github-action@master
        with:
          command: cp
          source: s3://...
          destination: ~/bin/cli
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
